### ISSUE TITLE
The error "Failed to establish a new connection to local host on port 7860"

### ISSUE THREAD

**Issue by qqq-gif** [ciodar/cultural-heritage-image2text#3]
![屏幕截图 2024-06-06 154741](https://github.com/ciodar/cultural-heritage-diffaug/assets/171913241/1ea9d13b-d287-4fec-9de6-ab1b97c01b6d)
How should this issue be resolved? Do I need to download the Stable Diffusion software?

**Comment by ciodar** [comment]
Yes, the augmentation script uses the [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) service. You should get the service running on your local machine or provide the URL to a server. You can find the installation and configuration details [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
